In [748]:
import pandas as pd
from glob import glob, glob1

In [749]:
path = './txtFile/'

data = pd.DataFrame(columns=['doc_id', 'document'])
for i in glob1(path, '*'):
    with open(path + i, 'r', encoding='utf8') as f:
        doc_line = []
        doc_id = i.split('.')[-2]

        for j in f:
            line = j.strip()
            doc_line.append(line)
        doc_details = ' '.join(doc_line)

        data = data.append(
            {"doc_id": doc_id, "document": doc_details}, ignore_index=True)
    f.close()

display(data)


C:\Users\doonl\AppData\Local\Temp\ipykernel_68\1399302844.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(
C:\Users\doonl\AppData\Local\Temp\ipykernel_68\1399302844.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(
C:\Users\doonl\AppData\Local\Temp\ipykernel_68\1399302844.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(
C:\Users\doonl\AppData\Local\Temp\ipykernel_68\1399302844.py:14: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  data = data.append(
C:\Users\doonl\AppData\Local\Temp\ipykernel_68\1399302844.py:14: FutureWarning: The frame.append method is deprecated an

doc_id                                           document
0      01  In the logistic management, the cost reduction...
1      02  Machine learning and predictive modeling have ...
2      03  Resource estimation is a technique that has ma...
3      04  Due to the emerging of Long Short-Term Memory ...
4      05  Since the spread of Coronavirus disease or Cov...
5      06  This thesis proposed a speech production acqui...
6      07  In recent studies, many NLP tasks could gain b...
7      08  The number of documents in a dataset available...
8      09  Understanding and interpretation of legislativ...
9      10  Word segmentation is an important pre-processi...
10     11  Loss estimation is considerably significant fo...
11     12  This thesis  presents a computational study on...
12     13  The financial problem is a challenging task fo...
13     14  Since a classical computer has a limitation to...
14     15  Hyperparameter Tuning chooses optimal hyperpar...
15     16  The honeybee is a social insect that communica...
16     17  System logs contain the complete information o...
17     18  Handling an imbalanced class problem is a chal...

In [750]:
data.head()

doc_id                                           document
0     01  In the logistic management, the cost reduction...
1     02  Machine learning and predictive modeling have ...
2     03  Resource estimation is a technique that has ma...
3     04  Due to the emerging of Long Short-Term Memory ...
4     05  Since the spread of Coronavirus disease or Cov...

In [751]:
len(data)

18

In [752]:
data['document'][17]

'Handling an imbalanced class problem is a challenging task in real-world applications. This problem affects various prediction models that predict only the majority classes and fail to identify the minority classes because of the skewed data. The oversampling technique is one of the exciting solutions that handles the imbalanced class problem. However, several existing oversampling methods do not consider the distribution of the target variable and cause an overlapping class problem. Therefore, this study introduces a new oversampling technique, namely Synthetic Minority Based on Probabilistic Distribution (SyMProD), to handle skewed datasets. Our method normalizes data using a Z-score and removes noisy data. Then, the proposed method selects minority samples based on the probability distribution of both classes. The synthetic instances are generated from the selected points and several minority nearest neighbors. Our technique aims to create synthetic instances that cover the minorit

In [753]:
from sklearn.feature_extraction.text import CountVectorizer
import nltk
from nltk.tokenize import word_tokenize
from nltk.stem import PorterStemmer
import re
import string
# s = set(string.punctuation)          # !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [754]:
def tok(text):
    # s = set(string.punctuation)          # !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
    tokens =  word_tokenize(text)
    tokens = list(filter(lambda token: token not in string.punctuation, tokens))
    return tokens


In [755]:
porter_stemmer = PorterStemmer()

def text_preprocessor(text):

    text = text.lower()
    text = re.sub("\\W", " ", text)  # remove special chars
    text = re.sub("\\s+(in|the|all|for|and|on)\\s+", " _connector_ ", text)  # normalize certain words

    # stem words
    words = re.split("\\s+", text)
    stemmed_words = [porter_stemmer.stem(word=word) for word in words]
    return ' '.join(stemmed_words)


In [756]:
cv = CountVectorizer(max_df = 0.9, min_df = 2, stop_words = 'english', tokenizer = tok, preprocessor = text_preprocessor)

In [757]:
dtm = cv.fit_transform(data['document'])

C:\Users\doonl\AppData\Roaming\Python\Python310\site-packages\sklearn\feature_extraction\text.py:404: UserWarning: Your stop_words may be inconsistent with your preprocessing. Tokenizing the stop words generated tokens ['abov', 'afterward', 'alon', 'alreadi', 'alway', 'ani', 'anoth', 'anyon', 'anyth', 'anywher', 'becam', 'becaus', 'becom', 'befor', 'besid', 'cri', 'describ', 'dure', 'els', 'elsewher', 'empti', 'everi', 'everyon', 'everyth', 'everywher', 'fifti', 'formerli', 'forti', 'ha', 'henc', 'hereaft', 'herebi', 'hi', 'howev', 'hundr', 'inde', 'latterli', 'mani', 'meanwhil', 'moreov', 'mostli', 'nobodi', 'noon', 'noth', 'nowher', 'onc', 'onli', 'otherwis', 'ourselv', 'perhap', 'pleas', 'seriou', 'sever', 'sinc', 'sincer', 'sixti', 'someon', 'someth', 'sometim', 'somewher', 'themselv', 'thenc', 'thereaft', 'therebi', 'therefor', 'thi', 'thu', 'togeth', 'twelv', 'twenti', 'veri', 'wa', 'whatev', 'whenc', 'whenev', 'wherea', 'whereaft', 'wherebi', 'wherev', 'whi', 'yourselv'] not in 

In [758]:
dtm

<18x292 sparse matrix of type '<class 'numpy.int64'>'
	with 969 stored elements in Compressed Sparse Row format>

In [759]:
from sklearn.decomposition import LatentDirichletAllocation

In [760]:
LDA = LatentDirichletAllocation(n_components = 3, random_state=15)

In [761]:
LDA.fit(dtm)

LatentDirichletAllocation(n_components=3, random_state=15)

In [762]:
#Grab the vocab of words

In [763]:
len(cv.get_feature_names())

C:\Users\doonl\AppData\Roaming\Python\Python310\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


292

In [764]:
type(cv.get_feature_names())

list

In [765]:
import random

random_word_id = random.randint(0, len(cv.get_feature_names()))
cv.get_feature_names()[random_word_id]

'effect'

In [766]:
#Grab the topics
len(LDA.components_)

3

In [767]:
type(LDA.components_)

numpy.ndarray

In [768]:
LDA.components_.shape

(3, 292)

In [769]:
LDA.components_

array([[ 0.3334385 ,  0.33337102,  0.33338235,  0.35714967,  0.33344134,
         0.33343062,  3.31026974,  0.33338235,  0.33342579,  4.3367053 ,
         0.33338361,  0.41673597,  1.33363132,  1.33478845,  2.33549205,
         2.29201097,  9.08559528,  0.3333857 ,  0.33350906,  0.33338881,
         1.33328252,  0.33338569,  0.4193286 ,  0.33879538,  1.33616147,
         2.65487446,  2.33409355,  0.33338887,  1.33366972,  8.13704362,
         1.33364464,  3.31027039,  4.33328657,  3.33565948,  1.33399347,
         4.34549833,  1.33140792,  0.33336942,  0.38257051,  0.33340514,
         0.33340901,  0.33338345,  2.29209797,  0.3333903 ,  1.32947316,
         3.33328531,  2.33328417,  0.33343225,  1.3343063 ,  1.33471542,
         0.40751451,  2.61261915,  1.3332631 ,  1.32527532,  0.33341957,
         0.3333955 ,  0.33338055,  2.33694105,  1.33473448,  1.33400803,
         0.33341452,  1.33280773,  1.33389069,  0.33338204,  1.33419945,
         1.33339333,  0.33342164,  0.33341928,  5.3

In [770]:
single_topic = LDA.components_[0]

In [771]:
single_topic.argsort()

array([253,  37,   1, 147, 251,  97, 152, 162, 195,  76, 223, 150, 181,
       169, 268, 264, 278, 279, 139,  56, 148,  91,  63,   2,   7,  74,
       151, 246, 154, 220,  41, 187, 197,  10, 106, 122,  21,  17, 219,
        19,  27, 228, 209,  99,  77, 116, 140, 178,  43, 189, 210,  55,
        78, 155, 142,  85,  98,  39, 161, 134, 114, 252,  40, 205, 103,
        60, 262, 238,  87, 163, 153,  67,  75,  54, 247,  66, 100, 165,
         8, 216, 135, 226,   5,  88, 243,  47, 108, 270, 112, 239,   0,
       170,   4, 265, 276, 149, 248, 232, 184, 194, 250, 126,  79, 241,
       231, 217, 132,  96, 131, 199, 202,  93, 237, 255, 289, 222, 286,
       157, 127,  18, 213,  23,  95, 229, 159, 225, 101, 290, 177,   3,
       118,  90, 206,  38,  50,  11, 256,  70,  22,  92, 277,  53, 109,
        44,  36, 173, 174, 259, 137, 107, 267, 244,  61, 111, 129, 212,
       143, 291, 201,  52, 186,  20,  65, 138,  81, 218, 180, 203,  12,
       254, 182, 190,  30, 215,  28, 102,  62, 188,  71, 266,  8

In [772]:
single_topic.argsort()[-10:]

array([193, 240, 196,  29,  16, 185, 275, 261, 166, 164], dtype=int64)

In [773]:
top_twenty_words = single_topic.argsort()[-20:]

In [774]:
for index in top_twenty_words:
    print(cv.get_feature_names()[index])

result
studi
select
data
machin
process
search
propos
problem
learn
paramet
set
perform
base
algorithm
optim
tune
techniqu
model
method


In [775]:
#Grab the highest probability words per topic

In [776]:
for i, topic in enumerate(LDA.components_):
    print(f"THE TOP 15 WORDS FOR TOPIC # {i}")
    print([cv.get_feature_names()[index] for index in topic.argsort()[-15:]])
    print('\n')
    print('\n')

THE TOP 15 WRODS FOR TOPIC # 0
['process', 'search', 'propos', 'problem', 'learn', 'paramet', 'set', 'perform', 'base', 'algorithm', 'optim', 'tune', 'techniqu', 'model', 'method']




THE TOP 15 WRODS FOR TOPIC # 1
['evalu', 'analysi', 'speech', 'featur', 'result', 'network', 'process', 'studi', 'dataset', 'wa', 'text', 'data', 's', 'use', 'model']




THE TOP 15 WRODS FOR TOPIC # 2
['appli', 'circuit', 'network', 'word', 'work', 'base', 'lstm', 'learn', 'data', 'languag', 'log', 'model', 'research', 'comput', 'use']






In [777]:
dtm

<18x292 sparse matrix of type '<class 'numpy.int64'>'
	with 969 stored elements in Compressed Sparse Row format>

In [778]:
topic_results = LDA.transform(dtm)

In [779]:
topic_results

array([[0.00533823, 0.99001889, 0.00464287],
       [0.99184026, 0.00409742, 0.00406232],
       [0.00337559, 0.00337378, 0.99325063],
       [0.00412203, 0.00419528, 0.99168269],
       [0.00402347, 0.86119689, 0.13477964],
       [0.00290737, 0.99417335, 0.00291928],
       [0.00630868, 0.98679733, 0.00689399],
       [0.00505383, 0.9893807 , 0.00556548],
       [0.00359785, 0.992775  , 0.00362715],
       [0.00832688, 0.00851681, 0.98315632],
       [0.00460482, 0.19918544, 0.79620974],
       [0.00532184, 0.98934068, 0.00533748],
       [0.37743834, 0.00449521, 0.61806644],
       [0.00405949, 0.18163958, 0.81430092],
       [0.99125817, 0.00430396, 0.00443787],
       [0.9913387 , 0.00439204, 0.00426925],
       [0.00393111, 0.00397038, 0.99209851],
       [0.99136205, 0.0044471 , 0.00419085]])

In [780]:
topic_results.shape

(18, 3)

In [781]:
topic_results[0].round(2)

array([0.01, 0.99, 0.  ])

In [782]:
data['document'][0]

'In the logistic management, the cost reduction for delivering the  goods to customer s is crucial to save the budget of the company . Since decades ago, various Vehicle Routing Problems (VRPs ) have been emerged enormously to improve the productivity and to reduce the logistic cost of the industry . Among them, Vehicle Routing Problem with Time Windows  (VRPTW ) is one of the most fundamental VRP variants and one of the most applicable variants in the real-world case studies. In this study , VRPTW with  hard time windows is solved  by developing a special Genetic Algorithm (GA), composed of a problem -specific crossover operator and seven different mutation operators. The proposed GA has better results with  the heuristic mutation among seven operators while exploring the new and better features in large search space. The results of the algorithm are tested on the popular Solomon benchmark 100 - customer datasets. The results show that the proposed GA is quite comparable  with the bes

In [783]:
topic_results[0].argmax()

1

In [784]:
data['Topic'] = topic_results.argmax(axis=1)

In [785]:
data

doc_id                                           document  Topic
0      01  In the logistic management, the cost reduction...      1
1      02  Machine learning and predictive modeling have ...      0
2      03  Resource estimation is a technique that has ma...      2
3      04  Due to the emerging of Long Short-Term Memory ...      2
4      05  Since the spread of Coronavirus disease or Cov...      1
5      06  This thesis proposed a speech production acqui...      1
6      07  In recent studies, many NLP tasks could gain b...      1
7      08  The number of documents in a dataset available...      1
8      09  Understanding and interpretation of legislativ...      1
9      10  Word segmentation is an important pre-processi...      2
10     11  Loss estimation is considerably significant fo...      2
11     12  This thesis  presents a computational study on...      1
12     13  The financial problem is a challenging task fo...      2
13     14  Since a classical computer has a limitation to...      2
14     15  Hyperparameter Tuning chooses optimal hyperpar...      0
15     16  The honeybee is a social insect that communica...      0
16     17  System logs contain the complete information o...      2
17     18  Handling an imbalanced class problem is a chal...      0

In [786]:
keywords = ['artificial intelligence',
            'genetic algorithm',
            'deep learning',
            'network resource planning',
            'audio-synchronization',
            'facial expression',
            'deep learning',
            'distributional reinforcement learning',
            'quantum random walk',
            'quantum computer simulator',
            'hyperparameter tuning',
            'random search',
            'convolutional neural networks',
            'feature extraction',
            'alice',
            'convolutional neural network',
            'classification',
            'probabilistic distribution',
            'genetic algorithm',
            'gradient boosting',
            'alice',
            'cern',
            'deep learning',
            'long short term memory',
            'abstractive text summarization',
            'covid-19',
            'acoustic-to-articulatory inversion',
            'deep learning',
            'natural language processing',
            'topic modeling',
            'document mining',
            'graph analysis',
            'natural language processing']


In [787]:
len(keywords)

33

In [788]:
from collections import Counter
c = Counter(keywords)
c

Counter({'artificial intelligence': 1,
         'genetic algorithm': 2,
         'deep learning': 4,
         'network resource planning': 1,
         'audio-synchronization': 1,
         'facial expression': 1,
         'distributional reinforcement learning': 1,
         'quantum random walk': 1,
         'quantum computer simulator': 1,
         'hyperparameter tuning': 1,
         'random search': 1,
         'convolutional neural networks': 1,
         'feature extraction': 1,
         'alice': 2,
         'convolutional neural network': 1,
         'classification': 1,
         'probabilistic distribution': 1,
         'gradient boosting': 1,
         'cern': 1,
         'long short term memory': 1,
         'abstractive text summarization': 1,
         'covid-19': 1,
         'acoustic-to-articulatory inversion': 1,
         'natural language processing': 2,
         'topic modeling': 1,
         'document mining': 1,
         'graph analysis': 1})